#!/usr/bin/env bash
# configured load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y

echo -e 'frontend arias.tech\n\tbind 0:80\n\tdefault_backend web_servers\n' >> /etc/haproxy/haproxy.cfg
echo -e 'backend web_servers\n\tbalance roundrobin\n\tserver 2224-web-01 35.196.67.203:80\n\tserver 2224-web-02 35.229.83.138:80\n' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
