#!/usr/bin/env bash
#holbertonscript.pid containing its PID
touch holbertonscript.pid
echo $$ >> holbertonscript.pid
sudo mv holbertonscript.pid /var/run/
while true; do
    trap "echo I hate the kill command && sudo rm /var/run/holbertonscript.pid && exit" SIGTERM SIGQUIT
    trap "echo Y U no love me?!" SIGINT
    echo "To infinity and beyond"
done
