#!/usr/bin/env bash
# print 10 times and Hi in 9th position

count=1
while [[ "$count" -le 10 ]]; do
    echo "Holberton School"
    if [ "$count" -eq 9 ]; then
	echo "Hi"
    fi
    count=$((count + 1))
done
