#!/usr/bin/env bash
# print 10 times and Hi in 9th position

count=1

while [[ "$count" -le 10 ]]; do
      if [ "$count" -eq 9 ]; then
      	 echo "Hi"
      else
	 echo "Holberton School"
      fi
      count=$((count + 1))
done
