#!/usr/bin/env bash
# loops from 1 to 10 bad luck 4 and good luck 8

count=1

while [[ "$count" -le 10 ]]; do
      if [ "$count" -eq 4 ]; then
      	 echo "bad luck"
      elif [[ "$count" -eq 8 ]]; then
      	 echo "good luck"
      else
	 echo "Holberton School"
      fi
      count=$((count + 1))
done
